import { Vazirmatn } from "next/font/google";
import "./globals.css";
import ClientLayout from "./clientLayout";

export const vazir = Vazirmatn({
  subsets: ["arabic"],
  variable: "--font-vazir",
  weight: ["400", "500", "700"]
});

export const metadata = {
  title: "Tree Structure",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" className={vazir.variable} dir="rtl">
      <body>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
